services:

  orthanc:
    image: orthancteam/orthanc:25.7.0
    container_name: orthanc
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - ./orthanc/orthanc-db:/var/lib/orthanc/db
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell -c \"from django.contrib.auth.models import User; 
             User.objects.filter(username='admin').exists() or 
             User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - orthanc
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    # volumes:
    #   - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend
    restart: unless-stopped
